export default function Hero() {
  return (
    <section className="relative isolate">
      {/* Subtle grid background (no rings) */}
      <div
        className="pointer-events-none absolute inset-0 -z-10 bg-background"
        aria-hidden
        style={{
          backgroundImage:
            "repeating-linear-gradient(0deg, color-mix(in oklch, var(--color-foreground) 5%, transparent) 0 1px, transparent 1px 160px), repeating-linear-gradient(90deg, color-mix(in oklch, var(--color-foreground) 5%, transparent) 0 1px, transparent 1px 160px)",
        }}
      />
      <div className="mx-auto max-w-6xl px-4 py-16 md:py-24">
        <div className="max-w-3xl">
          <h1 className="text-balance text-4xl font-semibold leading-tight tracking-[-0.02em] md:text-6xl lg:text-7xl">
            Turn any collection
            <br />
            into a perpetual machine
          </h1>
          <div className="mt-6 max-w-xl rounded-md border border-border/60 bg-secondary/30 p-4 text-sm text-muted-foreground">
            The protocol will automatically buy and list floor NFTs for a profit, using the trading fees generated by
            the token.
          </div>
          <div className="mt-4 flex flex-wrap items-center gap-3">
            <a
              href="/deployyoken"
              className="inline-flex h-8 items-center rounded-md bg-[var(--brand-lemon)] px-3 text-xs font-medium text-background"
            >
              Deploy a token
            </a>
            <a
              href="/browse"
              className="inline-flex h-8 items-center rounded-md border border-border/60 bg-transparent px-3 text-xs"
            >
              Browse Strategies™
            </a>
          </div>
        </div>
      </div>
    </section>
  )
}
